import { Link, useLocation } from 'react-router-dom';

export default function AboutPage() {
  const english = useLocation().pathname.startsWith('/en/');
  return <main className="bg-slate-950 text-white">
    <section className="mx-auto max-w-5xl px-6 py-20 lg:py-28">
      <p className="text-sm font-bold uppercase tracking-[0.24em] text-fuchsia-300">{english ? 'ABOUT AND EDITORIAL METHOD' : 'ACERCA DE Y MÉTODO EDITORIAL'}</p>
      <h1 className="mt-5 max-w-4xl text-4xl font-bold leading-tight lg:text-6xl">{english ? 'Music technology explained with practical tests, sources and honest limits.' : 'Tecnología musical explicada con pruebas prácticas, fuentes y límites honestos.'}</h1>
      <p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">{english ? 'MixingMusic.AI is a bilingual mixing and mastering platform founded by Daniel Palacio. Its knowledge center helps musicians understand audio engineering and AI-assisted music workflows without replacing listening, authorship or rights decisions.' : 'MixingMusic.AI es una plataforma bilingüe de mezcla y mastering fundada por Daniel Palacio. Su centro de conocimiento ayuda a músicos a entender ingeniería de audio y flujos asistidos por IA sin reemplazar escucha, autoría ni decisiones de derechos.'}</p>
    </section>
    <section className="bg-white text-slate-950"><div className="mx-auto grid max-w-5xl gap-10 px-6 py-16 md:grid-cols-2">
      <article><h2 className="text-3xl font-bold">{english ? 'How we publish' : 'Cómo publicamos'}</h2><ul className="mt-6 space-y-4 leading-7 text-slate-700">
        <li>{english ? 'We start from a real production question and explain the decision, not only a keyword.' : 'Partimos de una pregunta real de producción y explicamos la decisión, no solo una palabra clave.'}</li>
        <li>{english ? 'Changing product features, platform policies and legal guidance are linked to primary sources when available.' : 'Funciones cambiantes, políticas y orientación legal se enlazan a fuentes primarias cuando existen.'}</li>
        <li>{english ? 'We distinguish documented facts, practical judgment and limitations.' : 'Distinguimos hechos documentados, criterio práctico y limitaciones.'}</li>
        <li>{english ? 'We do not invent plugin chains, test results, affiliations or fixed settings.' : 'No inventamos cadenas de plugins, resultados de pruebas, asociaciones ni ajustes fijos.'}</li>
      </ul></article>
      <article><h2 className="text-3xl font-bold">{english ? 'What MixingMusic does' : 'Qué hace MixingMusic'}</h2><p className="mt-6 leading-7 text-slate-700">{english ? 'The product mixes stems supplied by the user and masters finished songs. Educational content may describe other platforms to explain a complete workflow, but trademarks belong to their owners and coverage does not imply partnership or endorsement.' : 'El producto mezcla stems suministrados por el usuario y masteriza canciones terminadas. El contenido educativo puede describir otras plataformas para explicar un flujo completo, pero las marcas pertenecen a sus titulares y la cobertura no implica asociación ni respaldo.'}</p><p className="mt-5 leading-7 text-slate-700">{english ? 'Mixing and mastering can improve balance, tone, dynamics and delivery. They cannot restore missing information, determine copyright ownership or guarantee acceptance by a distributor.' : 'La mezcla y el mastering pueden mejorar balance, tono, dinámica y entrega. No restauran información ausente, determinan titularidad ni garantizan aceptación de un distribuidor.'}</p></article>
      <article><h2 className="text-3xl font-bold">{english ? 'Corrections and updates' : 'Correcciones y actualizaciones'}</h2><p className="mt-6 leading-7 text-slate-700">{english ? 'Directories and policy-sensitive guides are reviewed when material changes are identified. A publication date is not a promise that every external product remains unchanged; readers should verify release-critical details on the linked official page.' : 'Directorios y guías sensibles a políticas se revisan cuando se identifican cambios materiales. La fecha no promete que cada producto externo siga igual; los detalles críticos deben verificarse en su página oficial.'}</p></article>
      <article><h2 className="text-3xl font-bold">{english ? 'Continue exploring' : 'Continúa explorando'}</h2><div className="mt-6 flex flex-col gap-3"><Link className="font-bold text-purple-700 underline" to={english ? '/en/blog' : '/blog'}>{english ? 'Mixing and mastering knowledge center' : 'Centro de conocimiento de mezcla y mastering'}</Link><Link className="font-bold text-purple-700 underline" to={`${english ? '/en' : ''}/blog/ai-music-prompts-free-100-prompts`}>{english ? '100 free AI music prompts' : '100 prompts de música IA gratis'}</Link><Link className="font-bold text-purple-700 underline" to={`${english ? '/en' : ''}/blog/top-100-ai-music-platforms-tools`}>{english ? '100 AI music platforms and tools' : '100 plataformas y herramientas de música IA'}</Link></div></article>
    </div></section>
  </main>;
}
