export type DirectoryLanguage = 'es' | 'en';

export type PluginCategory = 'compressor' | 'eq' | 'reverb' | 'tape' | 'channel-strip' | 'mastering' | 'vocal' | 'repair' | 'metering' | 'creative';

export interface AudioPlugin {
  slug: string;
  name: string;
  brand: 'universal-audio' | 'waves' | 'slate-digital' | 'izotope' | 'brainworx';
  category: PluginCategory;
  officialUrl: string;
  imageUrl?: string;
  imageCreditUrl?: string;
  summary: { es: string; en: string };
  bestFor: { es: string[]; en: string[] };
  note: { es: string; en: string };
}

export const VERIFIED_ON = '2026-08-19';

export const brandNames: Record<AudioPlugin['brand'], string> = {
  'universal-audio': 'Universal Audio', waves: 'Waves', 'slate-digital': 'Slate Digital', izotope: 'iZotope', brainworx: 'Brainworx',
};

export const categoryNames: Record<PluginCategory, { es: string; en: string }> = {
  compressor: { es: 'Compresores', en: 'Compressors' }, eq: { es: 'Ecualizadores', en: 'Equalizers' },
  reverb: { es: 'Reverbs', en: 'Reverbs' }, tape: { es: 'Cinta y saturación', en: 'Tape & saturation' },
  'channel-strip': { es: 'Canales completos', en: 'Channel strips' }, mastering: { es: 'Mastering', en: 'Mastering' },
  vocal: { es: 'Voces', en: 'Vocals' }, repair: { es: 'Restauración', en: 'Audio repair' },
  metering: { es: 'Medición', en: 'Metering' }, creative: { es: 'Efectos creativos', en: 'Creative effects' },
};

const wavesImage = (slug: string) => `https://www.waves.com/images/products/plugins/600/${slug}.png`;
const p = (plugin: AudioPlugin) => plugin;

export const audioPlugins: AudioPlugin[] = [
  p({ slug:'1176-classic-limiter-collection', name:'1176 Classic Limiter Collection', brand:'universal-audio', category:'compressor', officialUrl:'https://www.uaudio.com/products/1176-classic-limiter-collection', summary:{es:'Tres emulaciones del célebre limitador FET 1176 para controlar transientes con rapidez y añadir carácter.',en:'Three emulations of the celebrated 1176 FET limiter for fast transient control and unmistakable character.'}, bestFor:{es:['Voces','Baterías','Bajo'],en:['Vocals','Drums','Bass']}, note:{es:'Empieza con ratios 4:1 u 8:1 y ajusta la entrada hasta obtener el movimiento deseado.',en:'Start at 4:1 or 8:1 and drive the input until the gain reduction moves with the performance.'} }),
  p({ slug:'teletronix-la-2a-leveler-collection', name:'Teletronix LA-2A Leveler Collection', brand:'universal-audio', category:'compressor', officialUrl:'https://www.uaudio.com/products/teletronix-la-2a-leveler-collection', summary:{es:'Compresión óptica suave y musical para nivelar fuentes sin borrar su dinámica natural.',en:'Smooth, musical optical compression that levels sources without erasing their natural dynamics.'}, bestFor:{es:['Voces','Bajo','Guitarra limpia'],en:['Vocals','Bass','Clean guitar']}, note:{es:'Úsalo después de un compresor rápido para una cadena vocal en serie.',en:'Place it after a fast compressor for an effective serial vocal chain.'} }),
  p({ slug:'pultec-passive-eq-collection', name:'Pultec Passive EQ Collection', brand:'universal-audio', category:'eq', officialUrl:'https://www.uaudio.com/products/pultec-passive-eq-collection', summary:{es:'Ecualización pasiva modelada para graves sólidos, agudos sedosos y curvas amplias de tono.',en:'Modeled passive equalization for solid lows, silky highs, and broad musical tone shaping.'}, bestFor:{es:['Bus de mezcla','Bajo','Voces'],en:['Mix bus','Bass','Vocals']}, note:{es:'Prueba realce y atenuación simultáneos en graves para una curva resonante clásica.',en:'Try simultaneous low boost and attenuation for the classic resonant curve.'} }),
  p({ slug:'api-vision-channel-strip-collection', name:'API Vision Channel Strip Collection', brand:'universal-audio', category:'channel-strip', officialUrl:'https://www.uaudio.com/products/api-vision-channel-strip-collection', summary:{es:'Canal API completo con preamplificador, filtros, puerta, compresión y EQ proporcional Q.',en:'A complete API channel with preamp, filters, gate, compression, and proportional-Q EQ.'}, bestFor:{es:['Baterías','Guitarras','Mezcla rápida'],en:['Drums','Guitars','Fast mixing']}, note:{es:'Mantén una ganancia consistente entre módulos antes de juzgar el color.',en:'Keep level consistent between modules before judging the color.'} }),
  p({ slug:'studer-a800', name:'Studer A800 Tape Recorder', brand:'universal-audio', category:'tape', officialUrl:'https://www.uaudio.com/products/studer-a800', summary:{es:'Emulación multipista de cinta para cohesión, saturación y suavizado de transientes.',en:'Multitrack tape emulation for cohesion, saturation, and smoother transients.'}, bestFor:{es:['Pistas individuales','Baterías','Sintetizadores'],en:['Individual tracks','Drums','Synths']}, note:{es:'Alinea el nivel de salida: más volumen no equivale automáticamente a mejor sonido.',en:'Match the output level; louder is not automatically better.'} }),
  p({ slug:'capitol-chambers', name:'Capitol Chambers', brand:'universal-audio', category:'reverb', officialUrl:'https://www.uaudio.com/products/capitol-chambers', summary:{es:'Recreación de las cámaras subterráneas de Capitol Studios para profundidad y espacio orgánico.',en:'A recreation of Capitol Studios’ underground chambers for organic depth and space.'}, bestFor:{es:['Voces','Cuerdas','Baladas'],en:['Vocals','Strings','Ballads']}, note:{es:'Filtra graves en el retorno para conservar definición en la mezcla.',en:'High-pass the return to preserve clarity in the mix.'} }),
  p({ slug:'lexicon-224', name:'Lexicon 224 Digital Reverb', brand:'universal-audio', category:'reverb', officialUrl:'https://www.uaudio.com/products/lexicon-224', summary:{es:'Reverb digital de carácter vintage, reconocible por sus colas densas y moduladas.',en:'Vintage-character digital reverb known for dense, modulated tails.'}, bestFor:{es:['Voces pop','Cajas','Pads'],en:['Pop vocals','Snares','Pads']}, note:{es:'Sincroniza el pre-delay con el tempo para separar la fuente de la cola.',en:'Time the pre-delay to the tempo to separate the source from the tail.'} }),
  p({ slug:'empirical-labs-el8-distressor', name:'Empirical Labs EL8 Distressor', brand:'universal-audio', category:'compressor', officialUrl:'https://www.uaudio.com/products/empirical-labs-el8-distressor-compressor', summary:{es:'Compresor moderno y flexible que cubre control transparente, agresión y saturación armónica.',en:'A flexible modern compressor spanning transparent control, aggression, and harmonic saturation.'}, bestFor:{es:['Voces','Room de batería','Bajo'],en:['Vocals','Drum rooms','Bass']}, note:{es:'Usa el filtro del detector para evitar que el grave dispare demasiada compresión.',en:'Use the detector filter to keep low end from over-triggering compression.'} }),
  p({ slug:'manley-massive-passive', name:'Manley Massive Passive EQ', brand:'universal-audio', category:'eq', officialUrl:'https://www.uaudio.com/products/manley-massive-passive-eq', summary:{es:'EQ valvular de curvas amplias diseñado para decisiones tonales grandes y musicales.',en:'Tube equalizer with broad curves for large, musical tonal decisions.'}, bestFor:{es:['Mastering','Bus de mezcla','Voces'],en:['Mastering','Mix bus','Vocals']}, note:{es:'Haz movimientos pequeños y compara siempre al mismo volumen.',en:'Make small moves and always compare at matched loudness.'} }),
  p({ slug:'oxide-tape-recorder', name:'Oxide Tape Recorder', brand:'universal-audio', category:'tape', officialUrl:'https://www.uaudio.com/products/oxide-tape-recorder', summary:{es:'Cinta sencilla para sumar calidez, compresión natural y cohesión sin demasiados controles.',en:'A streamlined tape processor for warmth, natural compression, and cohesion without menu diving.'}, bestFor:{es:['Producción rápida','Buses','Instrumentos virtuales'],en:['Fast production','Buses','Virtual instruments']}, note:{es:'Aumenta Input para color y compensa con Output antes de decidir.',en:'Raise Input for color and compensate with Output before deciding.'} }),
  p({ slug:'neve-1073-preamp-eq', name:'Neve 1073 Preamp & EQ Collection', brand:'universal-audio', category:'eq', officialUrl:'https://www.uaudio.com/products/neve-1073-collection', summary:{es:'Modelado de previo y EQ 1073 para añadir peso, medios presentes y agudos musicales.',en:'Modeled 1073 preamp and EQ for weight, forward mids, and musical high-frequency shaping.'}, bestFor:{es:['Voces','Guitarras','Baterías'],en:['Vocals','Guitars','Drums']}, note:{es:'Conduce el previo para color, luego compensa la salida antes de comparar.',en:'Drive the preamp for color, then compensate the output before comparing.'} }),
  p({ slug:'ampex-atr-102', name:'Ampex ATR-102 Mastering Tape Recorder', brand:'universal-audio', category:'tape', officialUrl:'https://www.uaudio.com/products/ampex-atr-102', summary:{es:'Emulación de cinta estéreo de mastering para pulir transientes, densidad y tono final.',en:'Stereo mastering tape emulation for polished transients, density, and final tone.'}, bestFor:{es:['Bus de mezcla','Mastering','Efectos de cinta'],en:['Mix bus','Mastering','Tape effects']}, note:{es:'Elige fórmula y velocidad por el comportamiento del grave, no por una receta fija.',en:'Choose formula and speed by their low-end behavior, not by a fixed recipe.'} }),

  p({ slug:'renaissance-compressor', name:'Renaissance Compressor', brand:'waves', category:'compressor', officialUrl:'https://www.waves.com/plugins/renaissance-compressor', imageUrl:wavesImage('renaissance-compressor'), summary:{es:'Compresor directo y versátil con modos de carácter para control dinámico cotidiano.',en:'A direct, versatile compressor with character modes for everyday dynamics control.'}, bestFor:{es:['Voces','Bajo','Teclados'],en:['Vocals','Bass','Keys']}, note:{es:'Ajusta primero ataque y liberación escuchando el groove, no mirando el medidor.',en:'Set attack and release by listening to the groove, not watching the meter.'} }),
  p({ slug:'cla-76-compressor-limiter', name:'CLA-76 Compressor / Limiter', brand:'waves', category:'compressor', officialUrl:'https://www.waves.com/plugins/cla-76-compressor-limiter', imageUrl:wavesImage('cla-76-compressor-limiter-v2'), summary:{es:'Compresor FET inspirado en unidades clásicas para transientes rápidos y energía frontal.',en:'FET compressor inspired by classic units for fast transients and forward energy.'}, bestFor:{es:['Voces rock','Baterías','Bajo'],en:['Rock vocals','Drums','Bass']}, note:{es:'Un ataque no totalmente rápido suele dejar pasar más pegada.',en:'A less-than-fastest attack often lets more punch through.'} }),
  p({ slug:'cla-2a-compressor-limiter', name:'CLA-2A Compressor / Limiter', brand:'waves', category:'compressor', officialUrl:'https://www.waves.com/plugins/cla-2a-compressor-limiter', imageUrl:wavesImage('cla-2a-compressor-limiter'), summary:{es:'Nivelador óptico de operación simple para voces y bajos estables y cálidos.',en:'A simple optical leveler for stable, warm vocals and bass.'}, bestFor:{es:['Voces','Bajo','Guitarra'],en:['Vocals','Bass','Guitar']}, note:{es:'Busca reducción moderada y automatiza lo que el compresor no deba corregir.',en:'Aim for moderate reduction and automate what the compressor should not fix.'} }),
  p({ slug:'vocal-rider', name:'Vocal Rider', brand:'waves', category:'vocal', officialUrl:'https://www.waves.com/plugins/vocal-rider', imageUrl:wavesImage('vocal-rider'), summary:{es:'Automatiza el nivel vocal siguiendo la señal y un objetivo definido por el usuario.',en:'Automatically rides vocal level against a user-defined target.'}, bestFor:{es:['Voz principal','Podcast','Diálogo'],en:['Lead vocal','Podcast','Dialogue']}, note:{es:'Configura el rango de movimiento con moderación y escribe la automatización para editarla.',en:'Keep the movement range conservative and write the automation for later editing.'} }),
  p({ slug:'f6-floating-band-dynamic-eq', name:'F6 Floating-Band Dynamic EQ', brand:'waves', category:'eq', officialUrl:'https://www.waves.com/plugins/f6-floating-band-dynamic-eq', imageUrl:wavesImage('f6-floating-band-dynamic-eq'), summary:{es:'EQ dinámico de seis bandas para controlar resonancias sólo cuando se vuelven problemáticas.',en:'Six-band dynamic EQ for controlling resonances only when they become problematic.'}, bestFor:{es:['Voces','Bajo','Bus de mezcla'],en:['Vocals','Bass','Mix bus']}, note:{es:'Empieza con rangos pequeños para evitar que el timbre cambie demasiado.',en:'Start with small ranges to avoid changing the tone too much.'} }),
  p({ slug:'h-reverb-hybrid-reverb', name:'H-Reverb Hybrid Reverb', brand:'waves', category:'reverb', officialUrl:'https://www.waves.com/plugins/h-reverb-hybrid-reverb', imageUrl:wavesImage('h-reverb-hybrid-reverb'), summary:{es:'Reverb algorítmica flexible con modelado de entrada y herramientas detalladas para diseñar colas.',en:'Flexible algorithmic reverb with input modeling and detailed tail-design tools.'}, bestFor:{es:['Voces','Baterías','Diseño sonoro'],en:['Vocals','Drums','Sound design']}, note:{es:'Ajusta primero tiempo, pre-delay y filtros; añade modulación después.',en:'Set time, pre-delay, and filters first; add modulation afterward.'} }),
  p({ slug:'j37-tape', name:'Abbey Road J37 Tape', brand:'waves', category:'tape', officialUrl:'https://www.waves.com/plugins/j37-tape', imageUrl:wavesImage('j37-tape'), summary:{es:'Modelado de una grabadora de cinta de Abbey Road con saturación, wow, flutter y delay.',en:'Modeling of an Abbey Road tape machine with saturation, wow, flutter, and delay.'}, bestFor:{es:['Bus de batería','Voces','Efectos'],en:['Drum bus','Vocals','Effects']}, note:{es:'Usa wow y flutter con sutileza si buscas realismo y no un efecto evidente.',en:'Keep wow and flutter subtle when realism, rather than an obvious effect, is the goal.'} }),
  p({ slug:'ssl-ev2-channel', name:'SSL EV2 Channel', brand:'waves', category:'channel-strip', officialUrl:'https://www.waves.com/plugins/ssl-ev2-channel', imageUrl:wavesImage('ssl-ev2-channel'), summary:{es:'Canal SSL con filtros, dinámica y ecualización para un flujo de mezcla cohesivo.',en:'SSL channel strip with filters, dynamics, and EQ for a cohesive mixing workflow.'}, bestFor:{es:['Baterías','Guitarras','Mezcla completa'],en:['Drums','Guitars','Full mixes']}, note:{es:'Filtra antes de comprimir para que energía innecesaria no controle el detector.',en:'Filter before compression so unnecessary energy does not control the detector.'} }),
  p({ slug:'scheps-omni-channel-2', name:'Scheps Omni Channel 2', brand:'waves', category:'channel-strip', officialUrl:'https://www.waves.com/plugins/scheps-omni-channel', imageUrl:wavesImage('scheps-omni-channel-2'), summary:{es:'Canal modular con saturación, filtros, EQ, de-esser y dinámica para cadenas compactas.',en:'Modular channel strip with saturation, filters, EQ, de-essing, and dynamics in a compact chain.'}, bestFor:{es:['Voces','Baterías','Guitarras'],en:['Vocals','Drums','Guitars']}, note:{es:'Reordena los módulos según el problema; el orden cambia la respuesta.',en:'Reorder modules for the problem at hand; processor order changes the response.'} }),
  p({ slug:'l2-ultramaximizer', name:'L2 Ultramaximizer', brand:'waves', category:'mastering', officialUrl:'https://www.waves.com/plugins/l2-ultramaximizer', imageUrl:wavesImage('l2-ultramaximizer'), summary:{es:'Limitador brickwall y maximizador de nivel con dithering para mezcla y mastering.',en:'Brickwall limiter and level maximizer with dithering for mixing and mastering.'}, bestFor:{es:['Mastering','Buses','Control de picos'],en:['Mastering','Buses','Peak control']}, note:{es:'No persigas volumen a costa de bombeo o pérdida de transientes.',en:'Do not chase loudness at the cost of pumping or lost transients.'} }),
  p({ slug:'sibilance', name:'Sibilance', brand:'waves', category:'vocal', officialUrl:'https://www.waves.com/plugins/sibilance', imageUrl:wavesImage('sibilance'), summary:{es:'De-esser diseñado para detectar y reducir consonantes sibilantes conservando claridad vocal.',en:'De-esser designed to detect and reduce sibilant consonants while preserving vocal clarity.'}, bestFor:{es:['Voces','Diálogo','Coros'],en:['Vocals','Dialogue','Backing vocals']}, note:{es:'Escucha el modo de monitorización y reduce sólo la zona realmente sibilante.',en:'Use the monitor mode and reduce only the genuinely sibilant range.'} }),
  p({ slug:'curves-equator', name:'Curves Equator', brand:'waves', category:'eq', officialUrl:'https://www.waves.com/plugins/curves-equator', imageUrl:wavesImage('curves-equator'), summary:{es:'Procesador inteligente para atenuar resonancias problemáticas y equilibrar el espectro.',en:'Intelligent processor for attenuating problematic resonances and balancing the spectrum.'}, bestFor:{es:['Voces','Instrumentos','Bus de mezcla'],en:['Vocals','Instruments','Mix bus']}, note:{es:'Limita la profundidad del proceso para conservar el carácter original de la fuente.',en:'Limit processing depth to preserve the source’s original character.'} }),

  p({ slug:'vmr-3', name:'Virtual Mix Rack 3.0', brand:'slate-digital', category:'channel-strip', officialUrl:'https://slatedigital.com/vmr-3/', imageUrl:'https://slatedigital.com/wp-content/uploads/2024/12/VMR3-Rack-V1-transparent_crop.png', summary:{es:'Rack modular para combinar EQ, compresores, puertas y saturadores en una sola cadena.',en:'A modular rack for combining EQs, compressors, gates, and saturators in one chain.'}, bestFor:{es:['Mezcla completa','Voces','Baterías'],en:['Full mixes','Vocals','Drums']}, note:{es:'Construye una cadena corta y resuelve una función por módulo.',en:'Build a short chain and assign one clear job to each module.'} }),
  p({ slug:'virtual-tape-machines', name:'Virtual Tape Machines', brand:'slate-digital', category:'tape', officialUrl:'https://slatedigital.com/virtual-tape-machines/', summary:{es:'Emulación de máquinas de cinta multipista y mastering para densidad y cohesión.',en:'Emulation of multitrack and mastering tape machines for density and cohesion.'}, bestFor:{es:['Pistas','Buses','Mezcla'],en:['Tracks','Buses','Mixes']}, note:{es:'Compara con el mismo nivel y revisa el grave al cambiar velocidad de cinta.',en:'Level-match comparisons and check the low end when changing tape speed.'} }),
  p({ slug:'fg-x-2', name:'FG-X 2', brand:'slate-digital', category:'mastering', officialUrl:'https://slatedigital.com/fg-x-2/', summary:{es:'Suite de dinámica y limitación diseñada para aumentar nivel conservando impacto.',en:'Dynamics and limiting suite designed to raise level while retaining impact.'}, bestFor:{es:['Mastering','Premasters','Demos'],en:['Mastering','Premasters','Demos']}, note:{es:'Evalúa con referencias y deja margen para evitar decisiones sólo por volumen.',en:'Evaluate against references and leave margin to avoid loudness-only decisions.'} }),
  p({ slug:'infinity-eq-2', name:'Infinity EQ 2', brand:'slate-digital', category:'eq', officialUrl:'https://slatedigital.com/infinity-eq-2/', summary:{es:'Ecualizador moderno de flujo visual para corrección precisa y diseño tonal.',en:'Modern visual equalizer for precise correction and tonal shaping.'}, bestFor:{es:['Voces','Instrumentos','Buses'],en:['Vocals','Instruments','Buses']}, note:{es:'Usa el analizador como guía, pero confirma cada corte escuchando en contexto.',en:'Use the analyzer as a guide, but confirm every cut by listening in context.'} }),
  p({ slug:'metatune', name:'MetaTune', brand:'slate-digital', category:'vocal', officialUrl:'https://slatedigital.com/metatune/', summary:{es:'Afinación vocal en tiempo real con control de velocidad, nota y efecto creativo.',en:'Real-time vocal tuning with speed, note, and creative-effect control.'}, bestFor:{es:['Pop','Reggaeton','Efectos vocales'],en:['Pop','Reggaeton','Vocal effects']}, note:{es:'Define la tonalidad correcta antes de acelerar la corrección.',en:'Set the correct key before increasing correction speed.'} }),
  p({ slug:'fresh-air', name:'Fresh Air', brand:'slate-digital', category:'vocal', officialUrl:'https://slatedigital.com/fresh-air/', summary:{es:'Excitador de altas frecuencias de dos bandas para presencia y aire inmediatos.',en:'Two-band high-frequency exciter for immediate presence and air.'}, bestFor:{es:['Voces','Overheads','Bus acústico'],en:['Vocals','Overheads','Acoustic bus']}, note:{es:'Haz bypass frecuente: el brillo excesivo fatiga rápidamente.',en:'Bypass often; excessive brightness becomes fatiguing quickly.'} }),
  p({ slug:'metapitch', name:'MetaPitch', brand:'slate-digital', category:'creative', officialUrl:'https://slatedigital.com/metapitch/', summary:{es:'Cambio de tono y formato para armonías, dobles y diseño vocal creativo.',en:'Pitch and formant shifting for harmonies, doubles, and creative vocal design.'}, bestFor:{es:['Dobles vocales','Ad-libs','Diseño sonoro'],en:['Vocal doubles','Ad-libs','Sound design']}, note:{es:'Automatiza el formante independientemente del tono para resultados menos obvios.',en:'Automate formant independently from pitch for less obvious results.'} }),
  p({ slug:'thu-slate-edition', name:'TH-U Slate Edition', brand:'slate-digital', category:'creative', officialUrl:'https://slatedigital.com/thu/', summary:{es:'Suite de amplificadores, gabinetes y efectos para grabación y reamping de guitarra.',en:'Amp, cabinet, and effects suite for guitar recording and reamping.'}, bestFor:{es:['Guitarra eléctrica','Bajo','Reamping'],en:['Electric guitar','Bass','Reamping']}, note:{es:'Graba una DI limpia para poder cambiar amplificador y gabinete después.',en:'Record a clean DI so amp and cabinet choices can be changed later.'} }),

  p({ slug:'ozone-12-advanced', name:'Ozone 12 Advanced', brand:'izotope', category:'mastering', officialUrl:'https://www.izotope.com/products/ozone-advanced', summary:{es:'Suite modular de mastering con análisis asistido, EQ, dinámica, imagen y limitación.',en:'Modular mastering suite with assisted analysis, EQ, dynamics, imaging, and limiting.'}, bestFor:{es:['Mastering','Referencias','Entrega final'],en:['Mastering','References','Final delivery']}, note:{es:'Toma el asistente como punto de partida y valida cada módulo por separado.',en:'Treat the assistant as a starting point and validate each module separately.'} }),
  p({ slug:'ozone-12-standard', name:'Ozone 12 Standard', brand:'izotope', category:'mastering', officialUrl:'https://www.izotope.com/products/ozone-standard', summary:{es:'Conjunto central de herramientas de mastering para equilibrio tonal, dinámica y nivel final.',en:'Core mastering toolkit for tonal balance, dynamics, and final level.'}, bestFor:{es:['Home mastering','Demos','Streaming'],en:['Home mastering','Demos','Streaming']}, note:{es:'Compara con referencias normalizadas para no confundir nivel con calidad.',en:'Compare with loudness-matched references to avoid confusing level with quality.'} }),
  p({ slug:'neutron-5', name:'Neutron 5', brand:'izotope', category:'channel-strip', officialUrl:'https://www.izotope.com/products/neutron', summary:{es:'Suite de mezcla asistida con módulos para EQ, dinámica, excitación y balance entre pistas.',en:'Assisted mixing suite with modules for EQ, dynamics, excitation, and inter-track balance.'}, bestFor:{es:['Mezcla','Resolución de masking','Buses'],en:['Mixing','Masking control','Buses']}, note:{es:'Usa la asistencia para descubrir problemas; decide la intensidad escuchando toda la mezcla.',en:'Use assistance to find problems; choose intensity while hearing the whole mix.'} }),
  p({ slug:'nectar-4', name:'Nectar 4', brand:'izotope', category:'vocal', officialUrl:'https://www.izotope.com/products/nectar', summary:{es:'Cadena vocal integral con afinación, ecualización, dinámica, de-essing y efectos.',en:'Complete vocal chain with tuning, EQ, dynamics, de-essing, and effects.'}, bestFor:{es:['Voz principal','Coros','Podcast'],en:['Lead vocal','Backing vocals','Podcast']}, note:{es:'Corrige la grabación y edición antes de pedir a una cadena automática que lo haga todo.',en:'Fix recording and editing issues before asking an automatic chain to do everything.'} }),
  p({ slug:'rx-12-advanced', name:'RX 12 Advanced', brand:'izotope', category:'repair', officialUrl:'https://www.izotope.com/products/rx-advanced', summary:{es:'Suite de restauración espectral para ruido, clics, reverberación y problemas de diálogo.',en:'Spectral restoration suite for noise, clicks, reverb, and dialogue problems.'}, bestFor:{es:['Restauración','Diálogo','Grabaciones difíciles'],en:['Restoration','Dialogue','Difficult recordings']}, note:{es:'Procesa en pasadas ligeras; una reparación extrema puede crear artefactos.',en:'Process in light passes; extreme repair can create artifacts.'} }),
  p({ slug:'neoverb', name:'Neoverb', brand:'izotope', category:'reverb', officialUrl:'https://www.izotope.com/products/neoverb', summary:{es:'Reverb con mezcla de algoritmos y asistencia para diseñar espacios claros rápidamente.',en:'Reverb with algorithm blending and assistance for designing clear spaces quickly.'}, bestFor:{es:['Voces','Instrumentos','Producción rápida'],en:['Vocals','Instruments','Fast production']}, note:{es:'Haz sitio a la señal seca con pre-delay y ecualización del retorno.',en:'Make room for the dry signal with pre-delay and return EQ.'} }),
  p({ slug:'tonal-balance-control-3', name:'Tonal Balance Control 3', brand:'izotope', category:'metering', officialUrl:'https://www.izotope.com/products/tonal-balance-control', summary:{es:'Medidor comparativo que muestra la distribución espectral frente a objetivos de referencia.',en:'Comparative meter showing spectral distribution against reference targets.'}, bestFor:{es:['Mastering','Referencias','Control de traducción'],en:['Mastering','References','Translation checks']}, note:{es:'Úsalo como rango orientativo, nunca como una curva que toda canción deba copiar.',en:'Use it as a guide range, never as a curve every song must copy.'} }),
  p({ slug:'insight-2', name:'Insight 2', brand:'izotope', category:'metering', officialUrl:'https://www.izotope.com/products/insight', summary:{es:'Medición configurable de loudness, espectro, imagen estéreo e inteligibilidad.',en:'Configurable metering for loudness, spectrum, stereo image, and intelligibility.'}, bestFor:{es:['Mastering','Postproducción','Control de calidad'],en:['Mastering','Post-production','Quality control']}, note:{es:'Define el destino de entrega antes de interpretar loudness y picos verdaderos.',en:'Define the delivery target before interpreting loudness and true peak.'} }),

  p({ slug:'bx-console-amek-9099', name:'bx_console AMEK 9099', brand:'brainworx', category:'channel-strip', officialUrl:'https://www.brainworx.audio/products/brainworx/bx_console-amek-9099.html', summary:{es:'Canal analógico virtual de gran formato con dinámica, filtros, EQ y variación entre canales.',en:'Large-format virtual analog channel with dynamics, filters, EQ, and channel variation.'}, bestFor:{es:['Mezcla completa','Baterías','Buses'],en:['Full mixes','Drums','Buses']}, note:{es:'Usa tolerancias entre canales sólo cuando aporten dimensión, no por defecto.',en:'Use channel tolerances only when they add dimension, not by default.'} }),
  p({ slug:'bx-limiter-true-peak', name:'bx_limiter True Peak', brand:'brainworx', category:'mastering', officialUrl:'https://www.brainworx.audio/products/brainworx/bx_limiter-true-peak.html', summary:{es:'Limitador de pico verdadero orientado a loudness, control estéreo y entrega segura.',en:'True-peak limiter focused on loudness, stereo control, and safe delivery.'}, bestFor:{es:['Mastering','Streaming','Buses'],en:['Mastering','Streaming','Buses']}, note:{es:'Controla reducción de ganancia, LUFS y true peak como métricas distintas.',en:'Monitor gain reduction, LUFS, and true peak as separate metrics.'} }),
  p({ slug:'bx-masterdesk', name:'bx_masterdesk', brand:'brainworx', category:'mastering', officialUrl:'https://www.brainworx.audio/products/brainworx/bx_masterdesk.html', summary:{es:'Procesador de mastering simplificado para equilibrio, dinámica, estéreo y nivel final.',en:'Streamlined mastering processor for balance, dynamics, stereo, and final level.'}, bestFor:{es:['Demos','Mastering rápido','Referencias'],en:['Demos','Fast mastering','References']}, note:{es:'La sencillez acelera decisiones, pero no sustituye una mezcla equilibrada.',en:'The simplicity speeds decisions but does not replace a balanced mix.'} }),
  p({ slug:'bx-digital-v3', name:'bx_digital V3', brand:'brainworx', category:'eq', officialUrl:'https://www.brainworx.audio/products/brainworx/bx_digital-v3.html', summary:{es:'EQ de mastering Mid/Side con herramientas de monoización y control estéreo.',en:'Mid/Side mastering EQ with mono-maker and stereo-control tools.'}, bestFor:{es:['Mastering','Bus de mezcla','Imagen estéreo'],en:['Mastering','Mix bus','Stereo image']}, note:{es:'Comprueba siempre en mono después de modificar componentes Mid y Side.',en:'Always check mono compatibility after changing Mid and Side components.'} }),
  p({ slug:'bx-console-ssl-9000-j', name:'bx_console SSL 9000 J', brand:'brainworx', category:'channel-strip', officialUrl:'https://www.brainworx.audio/products/brainworx/bx_console-ssl-9000-j.html', summary:{es:'Emulación de consola SSL 9000 J para mezcla limpia, flexible y de alta definición.',en:'SSL 9000 J console emulation for clean, flexible, high-definition mixing.'}, bestFor:{es:['Pop','R&B','Mezcla completa'],en:['Pop','R&B','Full mixes']}, note:{es:'Usa el filtro pasa-altos antes de la dinámica para limpiar energía no musical.',en:'Use the high-pass filter before dynamics to remove non-musical energy.'} }),
  p({ slug:'bx-console-focusrite-sc', name:'bx_console Focusrite SC', brand:'brainworx', category:'channel-strip', officialUrl:'https://www.brainworx.audio/products/brainworx/bx_console-focusrite-sc.html', summary:{es:'Canal Focusrite Studio Console con EQ, dinámica y modelado de rutas analógicas.',en:'Focusrite Studio Console channel with EQ, dynamics, and modeled analog paths.'}, bestFor:{es:['Voces','Guitarras','Baterías'],en:['Vocals','Guitars','Drums']}, note:{es:'Decide primero si buscas corrección o color y ajusta la ganancia en consecuencia.',en:'Decide whether you need correction or color, then set gain accordingly.'} }),
  p({ slug:'black-box-hg-2ms', name:'Black Box HG-2MS', brand:'brainworx', category:'tape', officialUrl:'https://www.brainworx.audio/products/black-box-analog-design/hg-2ms.html', summary:{es:'Saturación valvular Mid/Side para densidad, armónicos y control del campo estéreo.',en:'Mid/Side tube saturation for density, harmonics, and stereo-field control.'}, bestFor:{es:['Bus de mezcla','Mastering','Bajo'],en:['Mix bus','Mastering','Bass']}, note:{es:'Iguala el volumen y añade armónicos en pequeñas dosis sobre material completo.',en:'Level-match and add harmonics in small doses on full-program material.'} }),
  p({ slug:'shadow-hills-mastering-compressor-class-a', name:'Shadow Hills Mastering Compressor Class A', brand:'brainworx', category:'compressor', officialUrl:'https://www.brainworx.audio/products/shadow-hills-industries/mastering-compressor-class-a.html', summary:{es:'Compresor de mastering de dos etapas con selección de transformador para color adicional.',en:'Two-stage mastering compressor with transformer choices for additional color.'}, bestFor:{es:['Mastering','Bus de mezcla','Baterías'],en:['Mastering','Mix bus','Drums']}, note:{es:'Reparte la reducción entre las etapas óptica y discreta en vez de forzar una sola.',en:'Share gain reduction between optical and discrete stages instead of forcing one.'} }),
  p({ slug:'spl-iron', name:'SPL IRON', brand:'brainworx', category:'compressor', officialUrl:'https://www.brainworx.audio/products/spl/iron.html', summary:{es:'Compresor vari-mu modelado para cohesión suave y color en buses y mastering.',en:'Modeled vari-mu compressor for smooth cohesion and color on buses and masters.'}, bestFor:{es:['Bus de mezcla','Mastering','Cuerdas'],en:['Mix bus','Mastering','Strings']}, note:{es:'Busca uno o dos decibelios de reducción si el objetivo es glue transparente.',en:'Aim for one or two decibels of reduction when transparent glue is the goal.'} }),
  p({ slug:'amek-eq-200', name:'AMEK EQ 200', brand:'brainworx', category:'eq', officialUrl:'https://www.brainworx.audio/products/amek/eq-200.html', summary:{es:'EQ paramétrico inspirado en mastering analógico para movimientos amplios y precisos.',en:'Parametric EQ inspired by analog mastering hardware for broad and precise moves.'}, bestFor:{es:['Mastering','Buses','Corrección tonal'],en:['Mastering','Buses','Tonal correction']}, note:{es:'Prioriza curvas amplias y movimientos pequeños sobre material estéreo.',en:'Favor broad curves and small moves on stereo material.'} }),
];

export const pluginByKey = Object.fromEntries(audioPlugins.map((plugin) => [`${plugin.brand}/${plugin.slug}`, plugin]));
export const pluginBrands = Object.keys(brandNames) as AudioPlugin['brand'][];
export const pluginCategories = Object.keys(categoryNames) as PluginCategory[];

const verifiedOfficialImages: Record<string, string> = {
  'pultec-passive-eq-collection': 'https://www.uaudio.com/cdn/shop/files/pultec_passive_eq_collection_gallery_1.png?v=1742249108&width=2048',
  'api-vision-channel-strip-collection': 'https://www.uaudio.com/cdn/shop/files/api_vision_channel_strip_collection_gallery_1.png?v=1742248767&width=2048',
  'studer-a800': 'https://www.uaudio.com/cdn/shop/files/studer_a800_multichannel_tape_recorder_gallery_1.png?v=1742248667&width=2048',
  'ozone-12-advanced': 'https://www.izotope.com/cdn/shop/files/ozone-12-advanced-image-01_d2753357-b799-498d-a566-dab001618419.png?v=1776675988&width=1400',
};

export const pluginImageUrl = (plugin: AudioPlugin) => plugin.imageUrl || verifiedOfficialImages[plugin.slug];

export const directoryPath = (lang: DirectoryLanguage) => lang === 'es' ? '/plugins-audio' : '/en/audio-plugins';
export const pluginPath = (plugin: AudioPlugin, lang: DirectoryLanguage) => lang === 'es' ? `/plugins/${plugin.brand}/${plugin.slug}` : `/en/plugins/${plugin.brand}/${plugin.slug}`;
export const brandPath = (brand: AudioPlugin['brand'], lang: DirectoryLanguage) => lang === 'es' ? `/plugins/marca/${brand}` : `/en/plugins/brand/${brand}`;
export const categoryPath = (category: PluginCategory, lang: DirectoryLanguage) => lang === 'es' ? `/plugins/categoria/${category}` : `/en/plugins/category/${category}`;

export const pluginDirectoryRoutes = [
  ...(['es','en'] as DirectoryLanguage[]).flatMap((lang) => [
    directoryPath(lang),
    ...pluginBrands.map((brand) => brandPath(brand, lang)),
    ...pluginCategories.map((category) => categoryPath(category, lang)),
    ...audioPlugins.map((plugin) => pluginPath(plugin, lang)),
  ]),
];
