ALTER TABLE public.mastering_orders
  DROP CONSTRAINT IF EXISTS mastering_orders_status_check;

ALTER TABLE public.mastering_orders
  ADD CONSTRAINT mastering_orders_status_check
  CHECK (status IN ('created', 'captured', 'failed', 'refunded'));

CREATE TABLE IF NOT EXISTS public.mastering_paypal_webhook_events (
  event_id text PRIMARY KEY,
  event_type text NOT NULL,
  resource_id text,
  order_id text,
  status text NOT NULL DEFAULT 'processing'
    CHECK (status IN ('processing', 'processed', 'ignored', 'failed')),
  error_code text,
  received_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz
);

ALTER TABLE public.mastering_paypal_webhook_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.mastering_paypal_webhook_events FROM PUBLIC, anon, authenticated;

CREATE INDEX IF NOT EXISTS mastering_paypal_webhook_order_idx
  ON public.mastering_paypal_webhook_events(order_id);

CREATE TABLE IF NOT EXISTS public.mastering_checkout_diagnostics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  order_id text,
  event_type text NOT NULL,
  error_code text,
  browser_context text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.mastering_checkout_diagnostics ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.mastering_checkout_diagnostics FROM PUBLIC, anon, authenticated;
CREATE INDEX IF NOT EXISTS mastering_checkout_diagnostics_created_idx
  ON public.mastering_checkout_diagnostics(created_at DESC);
